spring:
  datasource:
    url: jdbc:mysql://localhost:3306/huadi?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8
    username: root
    password: 466426
    driver-class-name: com.mysql.cj.jdbc.Driver

  thymeleaf:
    prefix: classpath:/templates/thymeleaf/
    check-template-location: true
    suffix: .html
    encoding: utf-8
    content-type: text/html
    mode: HTML5
    cache: false

  pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    pageSizeZero: count=countsql

  mvc:
    hiddenmethod:
      filter:
        enabled: true

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 1000MB